name: FRONTEND Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install frontend dependencies
        working-directory: spotify-analyzer
        run: npm install
        
      - name: Run frontend tests
        working-directory: spotify-analyzer
        run: npm test
